# In announce format $%user will be replaced by the tweeters name
# and $%text will be replaceed by the tweets text.
# you can use any colour code from this list http://ess.khhq.net/mc/
# AnnounceInterval is in secounds.

AnnounceFormat: "&7@&8$%user - &f$%text"
AnnounceInterval: 10
Users:
 - notch
 - jeb_

ResetConfig: false